// src/types/index.ts

export interface Vehicle {
  id: number;
  make: string;
  model: string;
  year: number;
  color?: string;
}

// Exception when POST / PUT (create/edit) (the id is generated by the DB or comes from URL)
export type VehicleInput = Omit<Vehicle, "id">;
